### ISSUE TITLE
[BUG] count_occurences

### ISSUE THREAD

**Issue by huybery** [kriadmin/30-seconds-of-python-code#20]
## [BUG] count_occurences

snippet is : 
```
from functools import reduce


def count_occurences(arr, val):
    return reduce(
        (lambda x, y: x + 1 if y == val and type(y) == type(val) else x + 0),
        arr)

count_occurences([1, 1, 2, 1, 2, 3], 1) # 3
```
but when I want to run that : 
```
count_occurences([2, 1, 2, 1, 2, 3], 1)  # 2
```
But it returns the count_occurences is 4. A mistake has happened. 
I think this code  run successfully only when the first element of list is 1 and the val is 1.
And I can't find a more pythonic code to repalce `list.count()`

**Comment by kriadmin** [comment]
I remember but testing it. But if you find qny solution just PR it. I am currently on my mobile so I will have to wait
