### ISSUE TITLE
[FEATURE] Change license to CC-0

### ISSUE THREAD

**Issue by koppor** [kriadmin/30-seconds-of-python-code#26]
The license of this repository is [GPL.3](https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)). The [30-seconds-of-javascript-code repo](https://github.com/Chalarangelo/30-seconds-of-code) has [CC-0](https://tldrlegal.com/license/creative-commons-cc0-1.0-universal). Since the code are snippets, why not having another license?

Superficially, GPL is equal to [CC-BY-SA](https://tldrlegal.com/license/creative-commons-attribution-sharealike-4.0-international-%28cc-by-sa-4.0%29). CC-BY-SA has been used until March 2016 by stackoverflow. Now, they changed to [MIT](https://tldrlegal.com/license/mit-license) + additional attribution. See https://meta.stackexchange.com/questions/272956/a-new-code-license-the-mit-this-time-with-attribution-required for a long justification.

In contrast to CC-BY-SA, GPL demands that each user of a code snippet has to disclose *all* code where this snippet is used. Is this really the intention of choosing GPL as license?

I would recommend to use the same license as the JavaScript sister site. It is very liberal. However, one has to accept that the code is donated to the public. I hope, this is acceptable.

**Comment by koppor** [comment]
This is what CC-0 is good for. See https://creativecommons.org/share-your-work/public-domain/cc0/ for their explanation.

> Affirmer offers the Work as-is and makes no representations or warranties of any kind concerning the Work, express, implied, statutory or otherwise, including without limitation warranties of title, merchantability, fitness for a particular purpose, non infringement, or the absence of latent or other defects, accuracy, or the present or absence of errors, whether or not discoverable, all to the greatest extent permissible under applicable law.

**Comment by kriadmin** [comment]
Okay as I soon as I get the time I will update the license.

**Comment by kriadmin** [comment]
Thank you for informing. 👍 
Updated the license
