### ISSUE TITLE
[BUG] website down (http://30secondsofpythoncode.ml)

### ISSUE THREAD

**Issue by Rob-Rychs** [kriadmin/30-seconds-of-python-code#28]
**Category:** 
### Description 

the website is down (http://30secondsofpythoncode.ml)

**Comment by kriadmin** [comment]
Sorry for the inconvenience but the domain name has expired. It was free but now comes for a price of about 10$. I have a personal domain which I am trying to setup with a sub-domain. The website should be up back soon :)

**Comment by kriadmin** [comment]
Fixed. The website is now available at python.kriadmin.me
