### ISSUE TITLE
Change array to lst or iterable

### ISSUE THREAD

**Issue by kriadmin** [kriadmin/30-seconds-of-python-code#29]
The affected snippets that need to be updated to use either the `iterable` or `lst` where appropriate are:

- [ ] bubble_sort
- [ ] chunk
- [ ] compact
- [ ] deep_flatten
- [ ] insertion-sort
- [ ] max_n
- [ ] min_n
- [ ] shuffle
- [ ] zip
 
First timers are encouraged to contribute to this.

**Comment by vignesh240** [comment]
I would like to fix this problem @kriadmin

**Comment by Rob-Rychs** [comment]
you should go for it @vignesh240!

**Comment by kriadmin** [comment]
Fixed via #31
