### ISSUE TITLE
[Question] average snippet references python2 in description? Typo?

### ISSUE THREAD

**Issue by Rob-Rychs** [kriadmin/30-seconds-of-python-code#32]
The snippet average mentions python2 in the snippet description but I thought this project was using 100% python3? If so the snippet description for average should probably be updated to not confuse people. It might also be a good idea to add a python3 badge to the top of the readme file so that it's obvious for new people/contributors.

**Category:**

**Comment by kriadmin** [comment]
@Rob-Rychs If you can, please submit a PR with the necessary changes.

**Comment by kriadmin** [comment]
Fixed via #33
