### ISSUE TITLE
Distinguish between lists and arrays

### ISSUE THREAD

**Issue by phihag** [kriadmin/30-seconds-of-python-code#5]
All throughout the snippets, text and variable names refer to arrays. In Python and other languages, arrays contain objects of the same type. The [`array` module](https://docs.python.org/dev/library/array.html) in the standard library implements this.

Instead, what is often meant is lists, or really, [iterables](https://docs.python.org/dev/glossary.html#term-iterable). Conversely, the variable name should be `lst` or `l` instead of `arr`.

**Comment by godaygo** [comment]
Generally I concur with @phihag  but instead of `lst` I suggest to follow the style used in the documentation of the `itertools` module from the standard library and use `iterable`.

https://docs.python.org/3/library/itertools.html

**Comment by ruth09** [comment]
1)Array is of fixed size once its ,where else in List it's dynamic can be append any n times.
2)most of the times array cannot be suitable for data structures because of its size limitations and stores only same data types, but in list it can be used in data structures.

**Comment by Rob-Rychs** [comment]
a python "flat list" is as close as you get to a JS-array round here 😀

**Comment by Rob-Rychs** [comment]
The affected snippets that need to be updated to use either the `iterable` or `lst` where appropriate are:

- [ ] bubble_sort
- [ ] chunk
- [ ] compact
- [ ] deep_flatten
- [ ] insertion-sort
- [ ] max_n
- [ ] min_n
- [ ] shuffle
- [ ] zip

maybe create some issues labeled as `first-timers-only` https://www.firsttimersonly.com/ for these @kriadmin what do you think?

**Comment by kriadmin** [comment]
@Rob-Rychs Yeah sure I will create one.

**Comment by kriadmin** [comment]
This issue has been replaced by #29
