### ISSUE TITLE
Return value is not true for is_upper_case("a3@$")

### ISSUE THREAD

**Issue by ZviKarp** [kriadmin/30-seconds-of-python-code#71]
### Expected Snippet Behavior

in 30-seconds-of-python-code/snippets/is_upper_case.md
      
```
is_upper_case('ABC') # True
is_upper_case('a3@$') # False
is_upper_case('aB4') # False
```
### Current Snippet Behavior

in 30-seconds-of-python-code/snippets/is_upper_case.md

```
is_upper_case('ABC') # True
is_upper_case('a3@$') # True
is_upper_case('aB4') # False
```

**Comment by OmarTahoun** [comment]
is this issue still open? i would like to fix that
