### ISSUE TITLE
[BUG] deep_flatten not working

### ISSUE THREAD

**Issue by meetzaveri** [kriadmin/30-seconds-of-python-code#9]
### Description 
The deep_flatten not working. Causing Error when I run it. (IDE - Pycharm)

### Expected Snippet Behavior
Should perform as expected

### Current Snippet Behavior
Error : NameError: global name 'deep' is not defined

### Possible Solution
Not at current, but will come up as early as possible

### ScreenShot
![error1pycharm](https://user-images.githubusercontent.com/21293048/36424615-f389b95a-1669-11e8-97b7-6c8ce28772af.png)

**Comment by kriadmin** [comment]
Yeah I know about that bug. If you want you can fix it. Just change `deep` to `deep_flatten`

**Comment by meetzaveri** [comment]
@kriadmin Okay i changed, but now output is empty. It's not showing anything.

**Comment by kriadmin** [comment]
![screenshot from 2018-02-20 18-37-41](https://user-images.githubusercontent.com/31792358/36425547-30216842-166d-11e8-9094-7f545f4b48a4.png)
It works perfectly fine for me

**Comment by meetzaveri** [comment]
Okay, problem should be from my end!

**Comment by kriadmin** [comment]
@meetzaveri Do you want to submit a PR for it? I am working on build scripts so I am a little busy right now. If you do submit one remember to add your name in `contributor_database`

**Comment by meetzaveri** [comment]
@kriadmin Okay I'll generate PR as you said. Sure I'll add my name in contributor_database

**Comment by meetzaveri** [comment]
@kriadmin So you can close this issue!
